[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "20"
PNPM_VERSION = "10.11.0"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[functions]
node_bundler = "esbuild"
